### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by dfdx** [dfdx/Milk.jl#1]
- [x] test nll
 - [x] incorporate CUDA codegen / `to_cuda_expr`
 - [x] run benchmarks on CuArrays
 - [x] plug in NNlib
 - [ ] create Conv module, create ConvNet example
